# Generated by Django 4.1.4 on 2022-12-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='url',
            field=models.URLField(),
        ),
    ]
