# Generated by Django 4.1.4 on 2022-12-10 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portafolio', '0003_alter_proyecto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='educacion')),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('enlace', models.URLField()),
                ('logo', models.ImageField(upload_to='tecnologias')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('logo', models.ImageField(upload_to='tecnologias')),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='usuarios')),
                ('rol', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('Educacion', models.ManyToManyField(to='portafolio.educacion')),
                ('idiomas', models.ManyToManyField(to='portafolio.idioma')),
                ('proyectos', models.ManyToManyField(to='portafolio.proyecto')),
                ('redesSociales', models.ManyToManyField(to='portafolio.redsocial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(to='portafolio.tecnologia'),
        ),
    ]
